### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by AnasIbrahim** [florianblume/6d-pat#121]
Hi,

When I try to build the project in QtCreator or from cmd line it fails.

In file included from ../../6d-pat-2.0/src/view/poseviewer/poseviewer.hpp:7,
                 from ../../6d-pat-2.0/src/view/mainwindow.hpp:7,
                 from ../../6d-pat-2.0/src/controller/poseseditingcontroller.hpp:8,
                 from ../../6d-pat-2.0/src/controller/poseseditingcontroller.cpp:1:
../../6d-pat-2.0/src/view/poseviewer/poseviewer3dwidget.hpp:4:10: fatal error: qt3dwidget.h: No such file or directory
    4 | #include "qt3dwidget.h"
      |          ^~~~~~~~~~~~~~

The build cannot find qt3dwidget.h

**Comment by AnasIbrahim** [comment]
I changed the include paths to relative and build is successful now. so I replace these two lines in src.pro from:
INCLUDEPATH += ../../../include/qt3dwidget
LIBS += -L../../../lib/qt3dwidget -lqt3dwidget

to:
INCLUDEPATH += $$PWD/../include/qt3dwidget
LIBS += -L$$PWD/../lib/qt3dwidget/ -lqt3dwidget

**Comment by florianblume** [comment]
Thanks, I'll look into this when I have time.

**Comment by florianblume** [comment]
There's also now an AppImage on the releases page which should work on Ubuntu without any additional requirements, everything ist packed inside.

**Comment by florianblume** [comment]
If you have feature requests or experience bugs feel free to open an issue. I'd be happy to look into them or get your fixes as pull requests!

**Comment by tobi1modna** [comment]
Hi florian. The "AppImage" was my first attempt to install the tool, but it doesn't work on my ubuntu 20.04 LTS. Also Docker gives me errors... so i came up with the building from source code and this way it works.
I sill have some small problems, which i don't understand if are problems on my machine, or bugs of the tool (for example, if i click on "tutorial screen" nothing appears)
Anyway, thanks so much for your willingness. Your tool could be a big breakthrough for my thesis work.

**Comment by florianblume** [comment]
Oh that's unfortunate to hear that the AppImage doesn't work, is there any output when you run it in the terminal? And what's the issue with Docker? That one should definitely work and works on my Ubuntu 20.04. About the tutorial screen, that is simply not implemented, yet, but I left it there to keep it in memory, maybe that was a bad idea :D You can check out the issues to see what I still want to implement. Are there any other issues I can help with? I'm glad to hear that it helps you! I spend a lot of sweat and blood on that program through my master's graduation and hoped that someone could use it :)

**Comment by florianblume** [comment]
Should be resolved in the latest release.
